### ISSUE TITLE
Container is running, but unable to access via localhost

### ISSUE THREAD

**Issue by nandgator** [linuxserver/docker-kdenlive#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

### Expected Behavior

Kdenlive is accessible at http://localhost:3000 

### Current Behavior

Connection is reset at the same URL.

### Steps to Reproduce

1. Here's my compose file.

    ```yml
    services:
      kdenlive:
        image: lscr.io/linuxserver/kdenlive:latest
        container_name: kdenlive
        security_opt:
          - seccomp:unconfined #optional
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Kolkata
          - SUBFOLDER=/root/projects #optional
          - KEYBOARD=en-us-qwerty #optional
        volumes:
          - $HOME/.config/kdenlive:/config
        ports:
          - 3000:3000
        devices:
          - /dev/dri:/dev/dri #optional
        shm_size: "1gb" #optional
        restart: unless-stopped
    ```

2. I have no other container running, and the port `3000` is free.
3. Try accessing http://localhost:3000 

### Environment

**OS:**: ArchLinux
**CPU architecture:** x86_64
**How podman service was installed:** From system package manager.

### Command used to create the container

```console
$ podman-compose -f kdenlive-app.yml up -d

['podman', '--version', '']
using podman version: 4.3.0
** excluding:  set()
['podman', 'network', 'exists', 'docker-compose_default']
podman run --name=kdenlive -d --security-opt seccomp=unconfined --label io.podman.compose.config-hash=123 --label io.podman.compose.project=docker-compose --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=docker-compose --label com.docker.compose.project.working_dir=~/Documents/03-Workspace/03-Experimentation/docker-compose --label com.docker.compose.project.config_files=kdenlive-app.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=kdenlive --device /dev/dri:/dev/dri -e PUID=1000 -e PGID=1000 -e TZ=Asia/Kolkata -e SUBFOLDER=/root/projects -e KEYBOARD=en-us-qwerty -v ~/.config/kdenlive:/root/.config/kdenlive --net docker-compose_default --network-alias kdenlive -p 3000:3000 --shm-size 1gb --restart unless-stopped lscr.io/linuxserver/kdenlive:latest
729cc84f0ace66b946bd63bc05fcf4fcc2dde853cbf3c221a1e597dfe757ef73
exit code: 0
```

### Container log:

    ~
    » podman logs -f kdenlive                             
    [custom-init] No custom services found, skipping...
    [migrations] started
    [migrations] no migrations found
    
    -------------------------------------
            _         ()
            | |  ___   _    __
            | | / __| | |  /  \
            | | \__ \ | | | () |
            |_| |___/ |_|  \__/
    
    
    Brought to you by linuxserver.io
    -------------------------------------
    
    To support LSIO projects visit:
    https://www.linuxserver.io/donate/
    -------------------------------------
    GID/UID
    -------------------------------------
    
    User uid:    1000
    User gid:    1000
    -------------------------------------
    
    
    Generating 2048 bit rsa key...
    
    ssl_gen_key_xrdp1 ok
    
    saving to rsakeys.ini
    
    .......+..+.+...........+....+......+.........+..+...+.+.........+.................+...+......+......+...+....+...+...+.....+......+...++++++++++++++++++++++++++++++++++
    +++++++++++++++++++++++++++++++*..+......+..+............+.........+.+...+..+......+.......+..+...............++++++++++++++++++++++++++++
    +++++++++++++++++++++++++++++++++++++*..+....+..+.+.........+.....+.+..+.......+...+........+...+.......+...+.........+........+.......+..+......+.............+.....
    +.+.......................+.+.........+...+.....+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ..+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+...+..+.+.........+..+...+.......+......+...+......
    ....................+...+...............+...+...+.+......+...............+..+.+...........+....+..+..........+.....+.......+..+.+........+......+....++++++++++++++++++++++++++++++
    +++++++++++++++++++++++++++++++++++*..........+...+.+......+...........+...+.+...........+....+......+..+.......+......+...+..............+............+.........+.........+..
    .+.............+.........+.....+.+..+...+....+..+...+.+......+.....+......+...+....+........+...+.......+............+.....+.......+...+..+.........+.+.........+..+.........+...+......+.......+...+..+....+.....
    +................+.....+...+..........+......+...+.....+.+............+.................+......+..........+..+...+......+.+..............+.............+......+.........+.....+...+...+..........+..+....+......+...+......+.
    ....+....+..+...+.+......+..+.......+.....+......+...+..........+..+....+........+...+....+...+...............+..+..................+.......+..............+.......+...+............+.....+....+.....+......+...+.+++
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    -----
    [custom-init] No custom files found, skipping...
